### ISSUE TITLE
Semantic segmentation

### ISSUE THREAD

**Issue by dhruti96shah** [buni-rock/Pixie#2]
Hello!
I am running the StartPixie.sh from the Deliverables folder. Semantic segmentation does not work. I am doing the following steps:
1. Click on Scribble and then the + sign
2. Draw bounding box, new window appears
3. Mark 'bkg' and 'obj' on left frame
4. Select 'Run matting'

The frame on the right still remains all red with no segmentation.
Could you please help?

Thanks!

**Comment by buni-rock** [comment]
Hi,

I think the issue is that the tool is not intuitive enough; for that, please have a look on our [User manual](https://github.com/buni-rock/Pixie/wiki/User-Manual) 

Under [Semantic segmentation](https://github.com/buni-rock/Pixie/wiki/User-Manual#semantic-segmentation) you can find a small **_how to_** on how to use it. 

If this doesn't help you, please provide us the log file (stored under Deliverables/log)

**Comment by olimpiapopica** [comment]
We will improve the way the buttons are displayed, in such a way as to have it more intuitive.

Meanwhile, could you, please, provide us the log file, in order to see if there are any errors inside?

Happy coding!
